export const coursesDummyData = [
  {
    id: "1",
    title:
      "Gapai Karier Impianmu sebagai Seorang UI/UX Designer & Product Manager.",
    category: "desain",
    courseImage: "https://video-belajar.netlify.app/courses/1.jpg",
    description:
      "Belajar bersama tutor profesional di Video Course. Kapanpun, di manapun.",
    mentor: "Jenna Ortega",
    mentorsRole: "Senior Accountant",
    mentorsWorkplace: "Gojek",
    mentorsAvatar: "/avatar/1.png",
    rating: "3.5",
    totalRating: "86",
    price: "Rp 300K",
    priceBeforeDiscount: "Rp 500K",
    discount: "50%",
    longDescription:
      "Foundations of User Experience (UX) Design adalah yang pertama dari rangkaian tujuh kursus yang akan membekali Anda dengan keterampilan yang dibutuhkan untuk melamar pekerjaan tingkat pemula dalam desain pengalaman pengguna. Desainer UX fokus pada interaksi yang dilakukan orang dengan produk seperti situs web, aplikasi seluler, dan objek fisik. Desainer UX membuat interaksi sehari-hari itu dapat digunakan, menyenangkan, dan dapat diakses. Peran seorang desainer UX tingkat pemula mungkin termasuk berempati dengan pengguna, menentukan poin rasa sakit mereka, memunculkan ide untuk solusi desain, membuat wireframe, prototipe, dan maket, dan menguji desain untuk mendapatkan umpan balik.",
  },
  {
    id: "2",
    title: "Big 4 Auditor Financial Analyst",
    category: "desain",
    courseImage: "/courses/2.jpg",
    description:
      "Mulai transformasi dengan instruktur profesional, harga yang terjangkau, dan kurikulum terbaik",
    mentor: "Jenna Ortega",
    mentorsRole: "Senior Programmer",
    mentorsWorkplace: "Tokopedia",
    mentorsAvatar: "/avatar/2.png",
    rating: "3.5",
    totalRating: "86",
    price: "Rp 300K",
    priceBeforeDiscount: "Rp 500K",
    discount: "50%",
    longDescription:
      "Foundations of User Experience (UX) Design adalah yang pertama dari rangkaian tujuh kursus yang akan membekali Anda dengan keterampilan yang dibutuhkan untuk melamar pekerjaan tingkat pemula dalam desain pengalaman pengguna. Desainer UX fokus pada interaksi yang dilakukan orang dengan produk seperti situs web, aplikasi seluler, dan objek fisik. Desainer UX membuat interaksi sehari-hari itu dapat digunakan, menyenangkan, dan dapat diakses. Peran seorang desainer UX tingkat pemula mungkin termasuk berempati dengan pengguna, menentukan poin rasa sakit mereka, memunculkan ide untuk solusi desain, membuat wireframe, prototipe, dan maket, dan menguji desain untuk mendapatkan umpan balik.",
  },
  {
    id: "3",
    title:
      "Gapai Karier Impianmu sebagai Seorang UI/UX Designer & Product Manager.",
    category: "desain",
    courseImage: "/courses/3.jpg",
    description:
      "Belajar bersama tutor profesional di Video Course. Kapanpun, di manapun.",
    mentor: "Jenna Ortega",
    mentorsRole: "Senior Accountant",
    mentorsWorkplace: "Gojek",
    mentorsAvatar: "/avatar/3.png",
    rating: "3.5",
    totalRating: "86",
    price: "Rp 300K",
    priceBeforeDiscount: "Rp 500K",
    discount: "50%",
    longDescription:
      "Foundations of User Experience (UX) Design adalah yang pertama dari rangkaian tujuh kursus yang akan membekali Anda dengan keterampilan yang dibutuhkan untuk melamar pekerjaan tingkat pemula dalam desain pengalaman pengguna. Desainer UX fokus pada interaksi yang dilakukan orang dengan produk seperti situs web, aplikasi seluler, dan objek fisik. Desainer UX membuat interaksi sehari-hari itu dapat digunakan, menyenangkan, dan dapat diakses. Peran seorang desainer UX tingkat pemula mungkin termasuk berempati dengan pengguna, menentukan poin rasa sakit mereka, memunculkan ide untuk solusi desain, membuat wireframe, prototipe, dan maket, dan menguji desain untuk mendapatkan umpan balik.",
  },
  {
    id: "4",
    title: "Big 4 Auditor Financial Analyst",
    category: "desain",
    courseImage: "/courses/4.jpg",
    description:
      "Mulai transformasi dengan instruktur profesional, harga yang terjangkau, dan kurikulum terbaik",
    mentor: "Jenna Ortega",
    mentorsRole: "Senior Programmer",
    mentorsWorkplace: "Tokopedia",
    mentorsAvatar: "/avatar/4.png",
    rating: "3.5",
    totalRating: "86",
    price: "Rp 300K",
    priceBeforeDiscount: "Rp 500K",
    discount: "50%",
    longDescription:
      "Foundations of User Experience (UX) Design adalah yang pertama dari rangkaian tujuh kursus yang akan membekali Anda dengan keterampilan yang dibutuhkan untuk melamar pekerjaan tingkat pemula dalam desain pengalaman pengguna. Desainer UX fokus pada interaksi yang dilakukan orang dengan produk seperti situs web, aplikasi seluler, dan objek fisik. Desainer UX membuat interaksi sehari-hari itu dapat digunakan, menyenangkan, dan dapat diakses. Peran seorang desainer UX tingkat pemula mungkin termasuk berempati dengan pengguna, menentukan poin rasa sakit mereka, memunculkan ide untuk solusi desain, membuat wireframe, prototipe, dan maket, dan menguji desain untuk mendapatkan umpan balik.",
  },
  {
    id: "5",
    title:
      "Gapai Karier Impianmu sebagai Seorang UI/UX Designer & Product Manager.",
    category: "desain",
    courseImage: "/courses/5.jpg",
    description:
      "Belajar bersama tutor profesional di Video Course. Kapanpun, di manapun.",
    mentor: "Jenna Ortega",
    mentorsRole: "Senior Accountant",
    mentorsWorkplace: "Gojek",
    mentorsAvatar: "/avatar/5.png",
    rating: "3.5",
    totalRating: "86",
    price: "Rp 300K",
    priceBeforeDiscount: "Rp 500K",
    discount: "50%",
    longDescription:
      "Foundations of User Experience (UX) Design adalah yang pertama dari rangkaian tujuh kursus yang akan membekali Anda dengan keterampilan yang dibutuhkan untuk melamar pekerjaan tingkat pemula dalam desain pengalaman pengguna. Desainer UX fokus pada interaksi yang dilakukan orang dengan produk seperti situs web, aplikasi seluler, dan objek fisik. Desainer UX membuat interaksi sehari-hari itu dapat digunakan, menyenangkan, dan dapat diakses. Peran seorang desainer UX tingkat pemula mungkin termasuk berempati dengan pengguna, menentukan poin rasa sakit mereka, memunculkan ide untuk solusi desain, membuat wireframe, prototipe, dan maket, dan menguji desain untuk mendapatkan umpan balik.",
  },
  {
    id: "6",
    title: "Big 4 Auditor Financial Analyst",
    category: "desain",
    courseImage: "/courses/6.jpg",
    description:
      "Mulai transformasi dengan instruktur profesional, harga yang terjangkau, dan kurikulum terbaik",
    mentor: "Jenna Ortega",
    mentorsRole: "Senior Programmer",
    mentorsWorkplace: "Tokopedia",
    mentorsAvatar: "/avatar/6.png",
    rating: "3.5",
    totalRating: "86",
    price: "Rp 300K",
    priceBeforeDiscount: "Rp 500K",
    discount: "50%",
    longDescription:
      "Foundations of User Experience (UX) Design adalah yang pertama dari rangkaian tujuh kursus yang akan membekali Anda dengan keterampilan yang dibutuhkan untuk melamar pekerjaan tingkat pemula dalam desain pengalaman pengguna. Desainer UX fokus pada interaksi yang dilakukan orang dengan produk seperti situs web, aplikasi seluler, dan objek fisik. Desainer UX membuat interaksi sehari-hari itu dapat digunakan, menyenangkan, dan dapat diakses. Peran seorang desainer UX tingkat pemula mungkin termasuk berempati dengan pengguna, menentukan poin rasa sakit mereka, memunculkan ide untuk solusi desain, membuat wireframe, prototipe, dan maket, dan menguji desain untuk mendapatkan umpan balik.",
  },
  {
    id: "7",
    title:
      "Gapai Karier Impianmu sebagai Seorang UI/UX Designer & Product Manager.",
    category: "desain",
    courseImage: "/courses/7.jpg",
    description:
      "Belajar bersama tutor profesional di Video Course. Kapanpun, di manapun.",
    mentor: "Jenna Ortega",
    mentorsRole: "Senior Accountant",
    mentorsWorkplace: "Gojek",
    mentorsAvatar: "/avatar/7.png",
    rating: "3.5",
    totalRating: "86",
    price: "Rp 300K",
    priceBeforeDiscount: "Rp 500K",
    discount: "50%",
    longDescription:
      "Foundations of User Experience (UX) Design adalah yang pertama dari rangkaian tujuh kursus yang akan membekali Anda dengan keterampilan yang dibutuhkan untuk melamar pekerjaan tingkat pemula dalam desain pengalaman pengguna. Desainer UX fokus pada interaksi yang dilakukan orang dengan produk seperti situs web, aplikasi seluler, dan objek fisik. Desainer UX membuat interaksi sehari-hari itu dapat digunakan, menyenangkan, dan dapat diakses. Peran seorang desainer UX tingkat pemula mungkin termasuk berempati dengan pengguna, menentukan poin rasa sakit mereka, memunculkan ide untuk solusi desain, membuat wireframe, prototipe, dan maket, dan menguji desain untuk mendapatkan umpan balik.",
  },
  {
    id: "8",
    title: "Big 4 Auditor Financial Analyst",
    category: "desain",
    courseImage: "/courses/8.jpg",
    description:
      "Mulai transformasi dengan instruktur profesional, harga yang terjangkau, dan kurikulum terbaik",
    mentor: "Jenna Ortega",
    mentorsRole: "Senior Programmer",
    mentorsWorkplace: "Tokopedia",
    mentorsAvatar: "/avatar/8.png",
    rating: "3.5",
    totalRating: "86",
    price: "Rp 300K",
    priceBeforeDiscount: "Rp 500K",
    discount: "50%",
    longDescription:
      "Foundations of User Experience (UX) Design adalah yang pertama dari rangkaian tujuh kursus yang akan membekali Anda dengan keterampilan yang dibutuhkan untuk melamar pekerjaan tingkat pemula dalam desain pengalaman pengguna. Desainer UX fokus pada interaksi yang dilakukan orang dengan produk seperti situs web, aplikasi seluler, dan objek fisik. Desainer UX membuat interaksi sehari-hari itu dapat digunakan, menyenangkan, dan dapat diakses. Peran seorang desainer UX tingkat pemula mungkin termasuk berempati dengan pengguna, menentukan poin rasa sakit mereka, memunculkan ide untuk solusi desain, membuat wireframe, prototipe, dan maket, dan menguji desain untuk mendapatkan umpan balik.",
  },
  {
    id: "9",
    title:
      "Gapai Karier Impianmu sebagai Seorang UI/UX Designer & Product Manager.",
    category: "desain",
    courseImage: "/courses/9.jpg",
    description:
      "Belajar bersama tutor profesional di Video Course. Kapanpun, di manapun.",
    mentor: "Jenna Ortega",
    mentorsRole: "Senior Accountant",
    mentorsWorkplace: "Gojek",
    mentorsAvatar: "/avatar/9.png",
    rating: "3.5",
    totalRating: "86",
    price: "Rp 300K",
    priceBeforeDiscount: "Rp 500K",
    discount: "50%",
    longDescription:
      "Foundations of User Experience (UX) Design adalah yang pertama dari rangkaian tujuh kursus yang akan membekali Anda dengan keterampilan yang dibutuhkan untuk melamar pekerjaan tingkat pemula dalam desain pengalaman pengguna. Desainer UX fokus pada interaksi yang dilakukan orang dengan produk seperti situs web, aplikasi seluler, dan objek fisik. Desainer UX membuat interaksi sehari-hari itu dapat digunakan, menyenangkan, dan dapat diakses. Peran seorang desainer UX tingkat pemula mungkin termasuk berempati dengan pengguna, menentukan poin rasa sakit mereka, memunculkan ide untuk solusi desain, membuat wireframe, prototipe, dan maket, dan menguji desain untuk mendapatkan umpan balik.",
  },
]

export const coursesDummyDataV2 = [
  {
    title:
      "Gapai Karier Impianmu sebagai Seorang UI/UX Designer & Product Manager.",
    category: "desain",
    courseImage: "/courses/1.jpg",
    description:
      "Belajar bersama tutor profesional di Video Course. Kapanpun, di manapun.",
    mentor: "Jenna Ortega",
    mentorsRole: "Senior Accountant",
    mentorsWorkplace: "Gojek",
    mentorsAvatar: "/avatar/1.png",
    rating: 3.5,
    totalRating: 86,
    price: 300000,
    priceBeforeDiscount: 350000,
    discount: 0.54,
    longDescription:
      "Foundations of User Experience (UX) Design adalah yang pertama dari rangkaian tujuh kursus yang akan membekali Anda dengan keterampilan yang dibutuhkan untuk melamar pekerjaan tingkat pemula dalam desain pengalaman pengguna. Desainer UX fokus pada interaksi yang dilakukan orang dengan produk seperti situs web, aplikasi seluler, dan objek fisik. Desainer UX membuat interaksi sehari-hari itu dapat digunakan, menyenangkan, dan dapat diakses. Peran seorang desainer UX tingkat pemula mungkin termasuk berempati dengan pengguna, menentukan poin rasa sakit mereka, memunculkan ide untuk solusi desain, membuat wireframe, prototipe, dan maket, dan menguji desain untuk mendapatkan umpan balik.",
    id: "1",
  },
  {
    title: "Menjadi Data Scientist Profesional",
    category: "teknologi",
    courseImage: "/courses/2.jpg",
    description:
      "Pelajari keterampilan data science bersama para ahli di bidangnya.",
    mentor: "Elon Musk",
    mentorsRole: "Data Scientist",
    mentorsWorkplace: "SpaceX",
    mentorsAvatar: "/avatar/2.png",
    rating: 4.8,
    totalRating: 152,
    price: 500000,
    priceBeforeDiscount: 600000,
    discount: 0.17,
    longDescription:
      "Kursus ini akan mengajarkan Anda dasar-dasar data science, mulai dari pengumpulan data hingga visualisasi. Anda akan belajar bagaimana menggunakan alat-alat seperti Python dan R untuk menganalisis data dan membuat model prediktif.",
    id: "2",
  },
  {
    title: "Belajar Machine Learning dari Dasar",
    category: "teknologi",
    courseImage: "/courses/3.jpg",
    description:
      "Kuasai konsep dasar machine learning dan mulai karier Anda di bidang ini.",
    mentor: "Andrew Ng",
    mentorsRole: "Machine Learning Specialist",
    mentorsWorkplace: "Google",
    mentorsAvatar: "/avatar/3.png",
    rating: 4.7,
    totalRating: 200,
    price: 450000,
    priceBeforeDiscount: 500000,
    discount: 0.1,
    longDescription:
      "Dalam kursus ini, Anda akan mempelajari dasar-dasar machine learning, termasuk supervised dan unsupervised learning, serta deep learning. Anda akan belajar bagaimana membangun model machine learning yang dapat digunakan untuk berbagai aplikasi.",
    id: "3",
  },
  {
    title: "Panduan Lengkap Digital Marketing",
    category: "pemasaran",
    courseImage: "/courses/4.jpg",
    description:
      "Pelajari strategi pemasaran digital terkini bersama para ahli.",
    mentor: "Neil Patel",
    mentorsRole: "Digital Marketer",
    mentorsWorkplace: "NP Digital",
    mentorsAvatar: "/avatar/4.png",
    rating: 4.5,
    totalRating: 180,
    price: 400000,
    priceBeforeDiscount: 450000,
    discount: 0.11,
    longDescription:
      "Kursus ini akan mengajarkan Anda tentang strategi pemasaran digital, termasuk SEO, SEM, dan pemasaran media sosial. Anda akan belajar bagaimana meningkatkan visibilitas online dan menarik lebih banyak pelanggan.",
    id: "4",
  },
  {
    title: "Menjadi Web Developer Handal",
    category: "teknologi",
    courseImage: "/courses/5.jpg",
    description: "Belajar membuat website profesional dari awal hingga mahir.",
    mentor: "Chris Coyier",
    mentorsRole: "Web Developer",
    mentorsWorkplace: "CSS-Tricks",
    mentorsAvatar: "/avatar/5.png",
    rating: 4.6,
    totalRating: 170,
    price: 350000,
    priceBeforeDiscount: 400000,
    discount: 0.12,
    longDescription:
      "Dalam kursus ini, Anda akan belajar cara membuat website dari dasar menggunakan HTML, CSS, dan JavaScript. Anda juga akan mempelajari framework populer seperti React dan Angular untuk membangun aplikasi web interaktif.",
    id: "5",
  },
  {
    title: "Kuasai Fotografi Profesional",
    category: "seni",
    courseImage: "/courses/6.jpg",
    description: "Belajar teknik fotografi dari fotografer profesional.",
    mentor: "Annie Leibovitz",
    mentorsRole: "Photographer",
    mentorsWorkplace: "Vogue",
    mentorsAvatar: "/avatar/6.png",
    rating: 4.9,
    totalRating: 210,
    price: 550000,
    priceBeforeDiscount: 600000,
    discount: 0.08,
    longDescription:
      "Kursus ini akan mengajarkan Anda teknik-teknik fotografi profesional, mulai dari komposisi hingga pengeditan. Anda akan belajar bagaimana menggunakan kamera DSLR dan software editing seperti Adobe Photoshop.",
    id: "6",
  },
  {
    title: "Menjadi Animator Profesional",
    category: "seni",
    courseImage: "/courses/7.jpg",
    description:
      "Pelajari animasi dari dasar hingga mahir bersama animator terkenal.",
    mentor: "John Lasseter",
    mentorsRole: "Animator",
    mentorsWorkplace: "Pixar",
    mentorsAvatar: "/avatar/7.png",
    rating: 4.8,
    totalRating: 195,
    price: 600000,
    priceBeforeDiscount: 700000,
    discount: 0.14,
    longDescription:
      "Dalam kursus ini, Anda akan belajar dasar-dasar animasi, termasuk prinsip-prinsip animasi dan teknik animasi 2D dan 3D. Anda juga akan mempelajari bagaimana menggunakan software animasi seperti Adobe Animate dan Blender.",
    id: "7",
  },
  {
    title: "Panduan Lengkap Membuat Startup",
    category: "bisnis",
    courseImage: "/courses/8.jpg",
    description: "Pelajari cara mendirikan dan mengelola startup sukses.",
    mentor: "Elon Musk",
    mentorsRole: "Entrepreneur",
    mentorsWorkplace: "Tesla",
    mentorsAvatar: "/avatar/8.png",
    rating: 4.7,
    totalRating: 220,
    price: 700000,
    priceBeforeDiscount: 800000,
    discount: 0.13,
    longDescription:
      "Kursus ini akan mengajarkan Anda tentang langkah-langkah untuk mendirikan startup, mulai dari ide hingga eksekusi. Anda akan belajar tentang model bisnis, pemasaran, dan pendanaan untuk startup.",
    id: "8",
  },
  {
    title: "Menjadi Ahli SEO",
    category: "pemasaran",
    courseImage: "/courses/9.jpg",
    description:
      "Pelajari teknik SEO untuk meningkatkan peringkat website Anda.",
    mentor: "Rand Fishkin",
    mentorsRole: "SEO Specialist",
    mentorsWorkplace: "Moz",
    mentorsAvatar: "/avatar/9.png",
    rating: 4.6,
    totalRating: 160,
    price: 350000,
    priceBeforeDiscount: 400000,
    discount: 0.12,
    longDescription:
      "Dalam kursus ini, Anda akan belajar tentang teknik SEO, termasuk keyword research, on-page SEO, dan off-page SEO. Anda juga akan mempelajari bagaimana mengukur dan meningkatkan performa SEO website Anda.",
    id: "9",
  },
  {
    title: "Kursus Komprehensif Project Management",
    category: "bisnis",
    courseImage: "/courses/10.jpg",
    description: "Belajar manajemen proyek dari dasar hingga mahir.",
    mentor: "PMI Certified",
    mentorsRole: "Project Manager",
    mentorsWorkplace: "PMP Institute",
    mentorsAvatar: "/avatar/10.png",
    rating: 4.5,
    totalRating: 180,
    price: 500000,
    priceBeforeDiscount: 550000,
    discount: 0.09,
    longDescription:
      "Kursus ini akan mengajarkan Anda prinsip-prinsip manajemen proyek, termasuk perencanaan, eksekusi, dan penutupan proyek. Anda akan belajar tentang metodologi manajemen proyek seperti Agile dan Scrum.",
    id: "10",
  },
  {
    title: "Menjadi Penulis Konten Profesional",
    category: "seni",
    courseImage: "/courses/11.jpg",
    description: "Pelajari cara menulis konten yang menarik dan efektif.",
    mentor: "Ann Handley",
    mentorsRole: "Content Writer",
    mentorsWorkplace: "MarketingProfs",
    mentorsAvatar: "/avatar/11.png",
    rating: 4.7,
    totalRating: 150,
    price: 300000,
    priceBeforeDiscount: 350000,
    discount: 0.14,
    longDescription:
      "Dalam kursus ini, Anda akan belajar teknik-teknik menulis konten untuk blog, website, dan media sosial. Anda juga akan mempelajari cara menulis yang menarik perhatian dan meningkatkan engagement.",
    id: "11",
  },
  {
    title: "Kursus Lengkap Copywriting",
    category: "pemasaran",
    courseImage: "/courses/12.jpg",
    description: "Belajar seni dan ilmu copywriting untuk pemasaran.",
    mentor: "David Ogilvy",
    mentorsRole: "Copywriter",
    mentorsWorkplace: "Ogilvy & Mather",
    mentorsAvatar: "/avatar/12.png",
    rating: 4.8,
    totalRating: 130,
    price: 450000,
    priceBeforeDiscount: 500000,
    discount: 0.1,
    longDescription:
      "Kursus ini akan mengajarkan Anda teknik-teknik copywriting yang efektif untuk iklan, email marketing, dan landing page. Anda akan belajar cara menulis copy yang menarik perhatian dan meningkatkan konversi.",
    id: "12",
  },
  {
    title: "Menjadi Software Engineer Profesional",
    category: "teknologi",
    courseImage: "/courses/13.jpg",
    description: "Belajar pemrograman dan pengembangan software dari dasar.",
    mentor: "Linus Torvalds",
    mentorsRole: "Software Engineer",
    mentorsWorkplace: "Linux Foundation",
    mentorsAvatar: "/avatar/13.png",
    rating: 4.9,
    totalRating: 250,
    price: 600000,
    priceBeforeDiscount: 700000,
    discount: 0.14,
    longDescription:
      "Dalam kursus ini, Anda akan belajar dasar-dasar pemrograman, termasuk algoritma dan struktur data. Anda juga akan mempelajari berbagai bahasa pemrograman seperti Python, Java, dan C++ serta teknik pengembangan software yang baik.",
    id: "13",
  },
  {
    title: "Belajar Bahasa Jepang dari Dasar",
    category: "bahasa",
    courseImage: "/courses/14.jpg",
    description:
      "Pelajari bahasa Jepang dengan cara yang menyenangkan dan interaktif.",
    mentor: "Hiroshi Yamamoto",
    mentorsRole: "Language Instructor",
    mentorsWorkplace: "Tokyo University",
    mentorsAvatar: "/avatar/14.png",
    rating: 4.6,
    totalRating: 140,
    price: 350000,
    priceBeforeDiscount: 400000,
    discount: 0.12,
    longDescription:
      "Kursus ini akan mengajarkan Anda dasar-dasar bahasa Jepang, termasuk tata bahasa, kosakata, dan kanji. Anda akan belajar melalui metode yang interaktif dan menyenangkan, sehingga memudahkan Anda untuk menguasai bahasa Jepang.",
    id: "14",
  },
  {
    title: "Menjadi Ahli UI/UX Design",
    category: "desain",
    courseImage: "/courses/15.jpg",
    description:
      "Pelajari prinsip-prinsip UI/UX Design dan aplikasikan dalam proyek nyata.",
    mentor: "Don Norman",
    mentorsRole: "UX Designer",
    mentorsWorkplace: "Nielsen Norman Group",
    mentorsAvatar: "/avatar/15.png",
    rating: 4.7,
    totalRating: 170,
    price: 400000,
    priceBeforeDiscount: 450000,
    discount: 0.11,
    longDescription:
      "Dalam kursus ini, Anda akan belajar dasar-dasar desain antarmuka pengguna (UI) dan pengalaman pengguna (UX). Anda akan mempelajari bagaimana membuat wireframe, prototipe, dan desain yang user-friendly.",
    id: "15",
  },
  {
    title: "Panduan Lengkap Menulis Novel",
    category: "seni",
    courseImage: "/courses/16.jpg",
    description: "Pelajari teknik menulis novel dari penulis terkenal.",
    mentor: "Stephen King",
    mentorsRole: "Author",
    mentorsWorkplace: "Self-Employed",
    mentorsAvatar: "/avatar/16.png",
    rating: 4.8,
    totalRating: 190,
    price: 450000,
    priceBeforeDiscount: 500000,
    discount: 0.1,
    longDescription:
      "Kursus ini akan mengajarkan Anda teknik-teknik menulis novel, mulai dari pengembangan karakter hingga plot. Anda akan belajar bagaimana menciptakan cerita yang menarik dan memikat pembaca.",
    id: "16",
  },
  {
    title: "Menjadi Ahli Keuangan Pribadi",
    category: "bisnis",
    courseImage: "/courses/17.jpg",
    description: "Pelajari cara mengelola keuangan pribadi dengan bijak.",
    mentor: "Dave Ramsey",
    mentorsRole: "Financial Advisor",
    mentorsWorkplace: "Ramsey Solutions",
    mentorsAvatar: "/avatar/17.png",
    rating: 4.6,
    totalRating: 130,
    price: 300000,
    priceBeforeDiscount: 350000,
    discount: 0.14,
    longDescription:
      "Dalam kursus ini, Anda akan belajar tentang dasar-dasar keuangan pribadi, termasuk pengelolaan anggaran, tabungan, dan investasi. Anda akan mempelajari strategi-strategi untuk mencapai kebebasan finansial.",
    id: "17",
  },
  {
    title: "Kursus Lengkap Desain Grafis",
    category: "desain",
    courseImage: "/courses/18.jpg",
    description: "Belajar desain grafis dari dasar hingga mahir.",
    mentor: "Paula Scher",
    mentorsRole: "Graphic Designer",
    mentorsWorkplace: "Pentagram",
    mentorsAvatar: "/avatar/18.png",
    rating: 4.8,
    totalRating: 220,
    price: 500000,
    priceBeforeDiscount: 550000,
    discount: 0.09,
    longDescription:
      "Kursus ini akan mengajarkan Anda dasar-dasar desain grafis, termasuk prinsip-prinsip desain, penggunaan warna, dan tipografi. Anda akan belajar bagaimana menggunakan software desain seperti Adobe Illustrator dan Photoshop.",
    id: "18",
  },
  {
    title: "Menjadi Ahli Cyber Security",
    category: "teknologi",
    courseImage: "/courses/19.jpg",
    description:
      "Pelajari cara melindungi sistem dan data dari ancaman keamanan.",
    mentor: "Kevin Mitnick",
    mentorsRole: "Cyber Security Specialist",
    mentorsWorkplace: "Mitnick Security",
    mentorsAvatar: "/avatar/19.png",
    rating: 4.7,
    totalRating: 180,
    price: 550000,
    priceBeforeDiscount: 600000,
    discount: 0.08,
    longDescription:
      "Dalam kursus ini, Anda akan belajar tentang dasar-dasar keamanan siber, termasuk enkripsi, jaringan, dan analisis risiko. Anda juga akan mempelajari teknik-teknik untuk melindungi sistem dan data dari serangan.",
    id: "19",
  },
  {
    title: "Belajar Bahasa Prancis dari Dasar",
    category: "bahasa",
    courseImage: "/courses/20.jpg",
    description:
      "Pelajari bahasa Prancis dengan metode yang interaktif dan efektif.",
    mentor: "Marie Dupont",
    mentorsRole: "Language Instructor",
    mentorsWorkplace: "Sorbonne University",
    mentorsAvatar: "/avatar/20.png",
    rating: 4.6,
    totalRating: 140,
    price: 350000,
    priceBeforeDiscount: 400000,
    discount: 0.12,
    longDescription:
      "Kursus ini akan mengajarkan Anda dasar-dasar bahasa Prancis, termasuk tata bahasa, kosakata, dan pelafalan. Anda akan belajar melalui metode yang interaktif dan menyenangkan untuk memudahkan Anda menguasai bahasa Prancis.",
    id: "20",
  },
]
