export const coursesDummyData = [
  {
    id: "1",
    title:
      "Gapai Karier Impianmu sebagai Seorang UI/UX Designer & Product Manager.",
    category: "desain",
    courseImage: "/courses/1.jpg",
    description:
      "Belajar bersama tutor profesional di Video Course. Kapanpun, di manapun.",
    mentor: "Jenna Ortega",
    mentorsRole: "Senior Accountant",
    mentorsWorkplace: "Gojek",
    mentorsAvatar: "/avatar/1.png",
    rating: "3.5",
    totalRating: "86",
    price: "Rp 300K",
    priceBeforeDiscount: "Rp 500K",
    discount: "50%",
    longDescription:
      "Foundations of User Experience (UX) Design adalah yang pertama dari rangkaian tujuh kursus yang akan membekali Anda dengan keterampilan yang dibutuhkan untuk melamar pekerjaan tingkat pemula dalam desain pengalaman pengguna. Desainer UX fokus pada interaksi yang dilakukan orang dengan produk seperti situs web, aplikasi seluler, dan objek fisik. Desainer UX membuat interaksi sehari-hari itu dapat digunakan, menyenangkan, dan dapat diakses. Peran seorang desainer UX tingkat pemula mungkin termasuk berempati dengan pengguna, menentukan poin rasa sakit mereka, memunculkan ide untuk solusi desain, membuat wireframe, prototipe, dan maket, dan menguji desain untuk mendapatkan umpan balik.",
  },
  {
    id: "2",
    title: "Big 4 Auditor Financial Analyst",
    category: "desain",
    courseImage: "/courses/2.jpg",
    description:
      "Mulai transformasi dengan instruktur profesional, harga yang terjangkau, dan kurikulum terbaik",
    mentor: "Jenna Ortega",
    mentorsRole: "Senior Programmer",
    mentorsWorkplace: "Tokopedia",
    mentorsAvatar: "/avatar/2.png",
    rating: "3.5",
    totalRating: "86",
    price: "Rp 300K",
    priceBeforeDiscount: "Rp 500K",
    discount: "50%",
    longDescription:
      "Foundations of User Experience (UX) Design adalah yang pertama dari rangkaian tujuh kursus yang akan membekali Anda dengan keterampilan yang dibutuhkan untuk melamar pekerjaan tingkat pemula dalam desain pengalaman pengguna. Desainer UX fokus pada interaksi yang dilakukan orang dengan produk seperti situs web, aplikasi seluler, dan objek fisik. Desainer UX membuat interaksi sehari-hari itu dapat digunakan, menyenangkan, dan dapat diakses. Peran seorang desainer UX tingkat pemula mungkin termasuk berempati dengan pengguna, menentukan poin rasa sakit mereka, memunculkan ide untuk solusi desain, membuat wireframe, prototipe, dan maket, dan menguji desain untuk mendapatkan umpan balik.",
  },
  {
    id: "3",
    title:
      "Gapai Karier Impianmu sebagai Seorang UI/UX Designer & Product Manager.",
    category: "desain",
    courseImage: "/courses/3.jpg",
    description:
      "Belajar bersama tutor profesional di Video Course. Kapanpun, di manapun.",
    mentor: "Jenna Ortega",
    mentorsRole: "Senior Accountant",
    mentorsWorkplace: "Gojek",
    mentorsAvatar: "/avatar/3.png",
    rating: "3.5",
    totalRating: "86",
    price: "Rp 300K",
    priceBeforeDiscount: "Rp 500K",
    discount: "50%",
    longDescription:
      "Foundations of User Experience (UX) Design adalah yang pertama dari rangkaian tujuh kursus yang akan membekali Anda dengan keterampilan yang dibutuhkan untuk melamar pekerjaan tingkat pemula dalam desain pengalaman pengguna. Desainer UX fokus pada interaksi yang dilakukan orang dengan produk seperti situs web, aplikasi seluler, dan objek fisik. Desainer UX membuat interaksi sehari-hari itu dapat digunakan, menyenangkan, dan dapat diakses. Peran seorang desainer UX tingkat pemula mungkin termasuk berempati dengan pengguna, menentukan poin rasa sakit mereka, memunculkan ide untuk solusi desain, membuat wireframe, prototipe, dan maket, dan menguji desain untuk mendapatkan umpan balik.",
  },
  {
    id: "4",
    title: "Big 4 Auditor Financial Analyst",
    category: "desain",
    courseImage: "/courses/4.jpg",
    description:
      "Mulai transformasi dengan instruktur profesional, harga yang terjangkau, dan kurikulum terbaik",
    mentor: "Jenna Ortega",
    mentorsRole: "Senior Programmer",
    mentorsWorkplace: "Tokopedia",
    mentorsAvatar: "/avatar/4.png",
    rating: "3.5",
    totalRating: "86",
    price: "Rp 300K",
    priceBeforeDiscount: "Rp 500K",
    discount: "50%",
    longDescription:
      "Foundations of User Experience (UX) Design adalah yang pertama dari rangkaian tujuh kursus yang akan membekali Anda dengan keterampilan yang dibutuhkan untuk melamar pekerjaan tingkat pemula dalam desain pengalaman pengguna. Desainer UX fokus pada interaksi yang dilakukan orang dengan produk seperti situs web, aplikasi seluler, dan objek fisik. Desainer UX membuat interaksi sehari-hari itu dapat digunakan, menyenangkan, dan dapat diakses. Peran seorang desainer UX tingkat pemula mungkin termasuk berempati dengan pengguna, menentukan poin rasa sakit mereka, memunculkan ide untuk solusi desain, membuat wireframe, prototipe, dan maket, dan menguji desain untuk mendapatkan umpan balik.",
  },
  {
    id: "5",
    title:
      "Gapai Karier Impianmu sebagai Seorang UI/UX Designer & Product Manager.",
    category: "desain",
    courseImage: "/courses/5.jpg",
    description:
      "Belajar bersama tutor profesional di Video Course. Kapanpun, di manapun.",
    mentor: "Jenna Ortega",
    mentorsRole: "Senior Accountant",
    mentorsWorkplace: "Gojek",
    mentorsAvatar: "/avatar/5.png",
    rating: "3.5",
    totalRating: "86",
    price: "Rp 300K",
    priceBeforeDiscount: "Rp 500K",
    discount: "50%",
    longDescription:
      "Foundations of User Experience (UX) Design adalah yang pertama dari rangkaian tujuh kursus yang akan membekali Anda dengan keterampilan yang dibutuhkan untuk melamar pekerjaan tingkat pemula dalam desain pengalaman pengguna. Desainer UX fokus pada interaksi yang dilakukan orang dengan produk seperti situs web, aplikasi seluler, dan objek fisik. Desainer UX membuat interaksi sehari-hari itu dapat digunakan, menyenangkan, dan dapat diakses. Peran seorang desainer UX tingkat pemula mungkin termasuk berempati dengan pengguna, menentukan poin rasa sakit mereka, memunculkan ide untuk solusi desain, membuat wireframe, prototipe, dan maket, dan menguji desain untuk mendapatkan umpan balik.",
  },
  {
    id: "6",
    title: "Big 4 Auditor Financial Analyst",
    category: "desain",
    courseImage: "/courses/6.jpg",
    description:
      "Mulai transformasi dengan instruktur profesional, harga yang terjangkau, dan kurikulum terbaik",
    mentor: "Jenna Ortega",
    mentorsRole: "Senior Programmer",
    mentorsWorkplace: "Tokopedia",
    mentorsAvatar: "/avatar/6.png",
    rating: "3.5",
    totalRating: "86",
    price: "Rp 300K",
    priceBeforeDiscount: "Rp 500K",
    discount: "50%",
    longDescription:
      "Foundations of User Experience (UX) Design adalah yang pertama dari rangkaian tujuh kursus yang akan membekali Anda dengan keterampilan yang dibutuhkan untuk melamar pekerjaan tingkat pemula dalam desain pengalaman pengguna. Desainer UX fokus pada interaksi yang dilakukan orang dengan produk seperti situs web, aplikasi seluler, dan objek fisik. Desainer UX membuat interaksi sehari-hari itu dapat digunakan, menyenangkan, dan dapat diakses. Peran seorang desainer UX tingkat pemula mungkin termasuk berempati dengan pengguna, menentukan poin rasa sakit mereka, memunculkan ide untuk solusi desain, membuat wireframe, prototipe, dan maket, dan menguji desain untuk mendapatkan umpan balik.",
  },
  {
    id: "7",
    title:
      "Gapai Karier Impianmu sebagai Seorang UI/UX Designer & Product Manager.",
    category: "desain",
    courseImage: "/courses/7.jpg",
    description:
      "Belajar bersama tutor profesional di Video Course. Kapanpun, di manapun.",
    mentor: "Jenna Ortega",
    mentorsRole: "Senior Accountant",
    mentorsWorkplace: "Gojek",
    mentorsAvatar: "/avatar/7.png",
    rating: "3.5",
    totalRating: "86",
    price: "Rp 300K",
    priceBeforeDiscount: "Rp 500K",
    discount: "50%",
    longDescription:
      "Foundations of User Experience (UX) Design adalah yang pertama dari rangkaian tujuh kursus yang akan membekali Anda dengan keterampilan yang dibutuhkan untuk melamar pekerjaan tingkat pemula dalam desain pengalaman pengguna. Desainer UX fokus pada interaksi yang dilakukan orang dengan produk seperti situs web, aplikasi seluler, dan objek fisik. Desainer UX membuat interaksi sehari-hari itu dapat digunakan, menyenangkan, dan dapat diakses. Peran seorang desainer UX tingkat pemula mungkin termasuk berempati dengan pengguna, menentukan poin rasa sakit mereka, memunculkan ide untuk solusi desain, membuat wireframe, prototipe, dan maket, dan menguji desain untuk mendapatkan umpan balik.",
  },
  {
    id:"8",
    title: "Big 4 Auditor Financial Analyst",
    category: "desain",
    courseImage: "/courses/8.jpg",
    description:
      "Mulai transformasi dengan instruktur profesional, harga yang terjangkau, dan kurikulum terbaik",
    mentor: "Jenna Ortega",
    mentorsRole: "Senior Programmer",
    mentorsWorkplace: "Tokopedia",
    mentorsAvatar: "/avatar/8.png",
    rating: "3.5",
    totalRating: "86",
    price: "Rp 300K",
    priceBeforeDiscount: "Rp 500K",
    discount: "50%",
    longDescription:
      "Foundations of User Experience (UX) Design adalah yang pertama dari rangkaian tujuh kursus yang akan membekali Anda dengan keterampilan yang dibutuhkan untuk melamar pekerjaan tingkat pemula dalam desain pengalaman pengguna. Desainer UX fokus pada interaksi yang dilakukan orang dengan produk seperti situs web, aplikasi seluler, dan objek fisik. Desainer UX membuat interaksi sehari-hari itu dapat digunakan, menyenangkan, dan dapat diakses. Peran seorang desainer UX tingkat pemula mungkin termasuk berempati dengan pengguna, menentukan poin rasa sakit mereka, memunculkan ide untuk solusi desain, membuat wireframe, prototipe, dan maket, dan menguji desain untuk mendapatkan umpan balik.",
  },
  {
    id: "9",
    title:
      "Gapai Karier Impianmu sebagai Seorang UI/UX Designer & Product Manager.",
    category: "desain",
    courseImage: "/courses/9.jpg",
    description:
      "Belajar bersama tutor profesional di Video Course. Kapanpun, di manapun.",
    mentor: "Jenna Ortega",
    mentorsRole: "Senior Accountant",
    mentorsWorkplace: "Gojek",
    mentorsAvatar: "/avatar/9.png",
    rating: "3.5",
    totalRating: "86",
    price: "Rp 300K",
    priceBeforeDiscount: "Rp 500K",
    discount: "50%",
    longDescription:
      "Foundations of User Experience (UX) Design adalah yang pertama dari rangkaian tujuh kursus yang akan membekali Anda dengan keterampilan yang dibutuhkan untuk melamar pekerjaan tingkat pemula dalam desain pengalaman pengguna. Desainer UX fokus pada interaksi yang dilakukan orang dengan produk seperti situs web, aplikasi seluler, dan objek fisik. Desainer UX membuat interaksi sehari-hari itu dapat digunakan, menyenangkan, dan dapat diakses. Peran seorang desainer UX tingkat pemula mungkin termasuk berempati dengan pengguna, menentukan poin rasa sakit mereka, memunculkan ide untuk solusi desain, membuat wireframe, prototipe, dan maket, dan menguji desain untuk mendapatkan umpan balik.",
  },
];
